// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:news_app/core/model/user_mdel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(UseerModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(UseerModelAdapter());
  }
}
